### ISSUE TITLE
More documentation - Supported Html?

### ISSUE THREAD

**Issue by emouawad** [thomasloven/lovelace-useful-markdown-card#13]
What other html tags does it support? i figured so far: ```<b> <i> <pre> <img> <center>```

i am trying to put a text next to an image - would it be possible to get something like style=""
For example, i can do: style="float: left;"

Maybe add ```<div>``` too just like the others that are already supported?

**Comment by thomasloven** [comment]
Behind the scenes this is a normal lovelace [markdown](https://www.home-assistant.io/lovelace/markdown/) card. So it supports the same tags as that.
I honestly don't know which ones that is, and can't really change it.
