### ISSUE TITLE
undefined sensor - display nothing

### ISSUE THREAD

**Issue by Tom-ahawk** [thomasloven/lovelace-useful-markdown-card#15]
Using your card with a sensor getting its data from a HiFi component. When the component is turned off, the sensor in HA lacks the attributes I am displaying in the useful-markdown-card.
![image](https://user-images.githubusercontent.com/35527507/56420604-f4a01f00-629e-11e9-8651-00171eecaf9e.png)

Would it be an idea, when a sensor/attribute is undefined, not displayed in the markdown card?

**Comment by thomasloven** [comment]
https://github.com/thomasloven/lovelace-useful-markdown-card#if
