### ISSUE TITLE
If statement weirdness?

### ISSUE THREAD

**Issue by TarheelGrad1998** [thomasloven/lovelace-useful-markdown-card#16]
It doesn't seem that the if statement is working properly?

I wanted to use this card to show me information and links to the details about updates.  But trying to conditionally show when there is an update doesn't seem to be working.  To wit:

```
content: |
  [[ sensor.version_current ]], [[ sensor.version_available ]]
  [[ if(sensor.version_current == sensor.version_available, "NO UPDATE", "UPDATE") ]]
```

Output:
0.92.1, 0.92.2
NO UPDATE

If I change to !=, it returns "UPDATE".

**Comment by thomasloven** [comment]
That's odd. Does it work if you use `sensor.version_current.state == sensor.version_available.state`?

**Comment by TarheelGrad1998** [comment]
Same result.
```
  [[ sensor.version_current.state ]], [[ sensor.version_available.state ]]

  [[ if(sensor.version_current.state == sensor.version_available.state, "NO
  UPDATE", "UPDATE") ]]
```
0.92.1, 0.92.2
NO UPDATE

Maybe it's somehow casting as numeric and thus losing the last .1/.2?

**Comment by TarheelGrad1998** [comment]
I believe I just confirmed some sort of cast:

```
  [[ if(sensor.version_current.state == "0.92", "=", "!=") ]]
  
  [[ if(sensor.version_current.state == "0.92.1", "=", "!=") ]]
  
  [[ if(sensor.version_current.state == "0.92.2", "=", "!=") ]]
  
  [[ if(sensor.version_current.state == "0.93.2", "=", "!=") ]]
  
```

Results:

=

=

=

!=

Any way to force a string comparison?

**Comment by thomasloven** [comment]
Try updating card tools.

**Comment by TarheelGrad1998** [comment]
I literally just installed it yesterday, and am running 0.4

**Comment by thomasloven** [comment]
I literally pushed an update (linked above) five minutes ago, based on your information 😉

**Comment by TarheelGrad1998** [comment]
Oops, sorry, I missed that detail.  

Works fine now.  Thanks for the prompt fix!

**Comment by thomasloven** [comment]
Thanks for the debugging help!
