### ISSUE TITLE
"mapping values" bug when ":" insert

### ISSUE THREAD

**Issue by neomvll** [thomasloven/lovelace-useful-markdown-card#17]
no errors:
[[ if(switch.sonoff_1010011010 == "off", "Good New, No Alarms!") ]] 

but if we insert a ":" like:
[[ if(switch.sonoff_10004118f9 == "off", "Good New: No Alarms!") ]]

error: "mapping values are not allowed here in "/config/ui-lovelace.yaml", line 39, column 66"

**Comment by thomasloven** [comment]
http://thomasloven.com/blog/2018/08/YAML-For-Nonprogrammers/
#18
