### ISSUE TITLE
cant be only [[ if... ]] ??

### ISSUE THREAD

**Issue by neomvll** [thomasloven/lovelace-useful-markdown-card#18]
no errors:
content: test
 [[ if(switch.sonoff_10101001 == "off", "Good News, No Alarms!") ]]

but if I remove the "test" word, even if I put a "else" statement, we got the error:
while parsing a flow sequence in "/config/ui-lovelace.yaml", line 39, column 16 expected ',' or ']', but got '<scalar>' in "/config/ui-lovelace.yaml", line 39, column 79

**Comment by neomvll** [comment]
I need more tests, but this works:
content: >
[[ if(switch.sonoff_10101001 == "off", "Good News, No Alarms!") ]]

**Comment by thomasloven** [comment]
That's yaml. Whatever you put in `content:` ends at the same time the line does, unless it's `content: |` or `content: >` in which case the following block (determined by indentation) is used as the input.
