### ISSUE TITLE
Padding applied with delay

### ISSUE THREAD

**Issue by Sholofly** [thomasloven/lovelace-useful-markdown-card#4]
Hi,

 When i open a view with this card on it, the padding is applied with delay. strange is, that's not always the same delay.  It varies from 1 to 3 seconds.

**Comment by thomasloven** [comment]
This card will be updated soon - once 0.84 has stabilized a bit more - that will be fixed then.

Actually, I forgot why I added padding as an option. Could you remind me of the use case?

**Comment by postlund** [comment]
This seems to still be an issue, did you find any time to fix this @thomasloven?

**Comment by thomasloven** [comment]
No, not yet. And I still can't remember why padding was added anyway. Would appreciate a use case.

**Comment by postlund** [comment]
The padding is needed to make the card look the same as all other cards, see images below.
![without_padding](https://user-images.githubusercontent.com/5982179/51831288-09999180-22f2-11e9-99bc-51b572477efd.png)
![with_padding](https://user-images.githubusercontent.com/5982179/51831289-09999180-22f2-11e9-86bf-3dbdc6f937f6.png)

**Comment by thomasloven** [comment]
Should be fixed now.
