### ISSUE TITLE
Can't include multiple entities on the same line

### ISSUE THREAD

**Issue by wklink** [thomasloven/lovelace-useful-markdown-card#7]
I used to be able to specify multiple entities on a single line, but that no longer works.  For example:

    [[ sensor.next_event.state ]]: [[ sensor.next_location.state ]]

With the latest version, I have to separate them with a blank line between them.  This does not work:

    [[ sensor.next_event.state ]]: 
    [[ sensor.next_location.state ]]

But this does:

    [[ sensor.next_event.state ]]: 

    [[ sensor.next_location.state ]]

The former would produce output like:

    Meeting: 123 Main Street

By requiring them to appear on separate lines, I can only get:

    Meeting:
    123 Main Street

**Comment by thomasloven** [comment]
Update card-tools.
