### ISSUE TITLE
Useful-markdown-card won't load on Chromebook

### ISSUE THREAD

**Issue by SteveDinn** [thomasloven/lovelace-useful-markdown-card#8]
I don't understand why, but useful-markdown-card won't load on my chromebook. It works on Chrome in Windows, and Chrome on Android, but not on the Chromebook.

I get this error (see screenshot):
![Screenshot 2019-03-08 at 20 59 52](https://user-images.githubusercontent.com/3911507/54063878-f7aae880-41e5-11e9-9a5f-bd039ad57e53.png)

The card is nested underneath other custom cards (vertical-stack-in-card), and I've tried the card-loader solution, but I get the same errors -- again, only on ChromeOS

**Comment by thomasloven** [comment]
Please confirm if the latest update fixes this.

**Comment by SteveDinn** [comment]
Updated to commit 68d0f49. Looks like this is still happening for me. Can I look at anything for you?

CARD-TOOLS IS INSTALLEDDeviceID: c73d0667-91af3e45
useful-markdown-card.js?v=2:2 Uncaught (in promise) TypeError: Class extends value undefined is not a constructor or null
    at customElements.whenDefined.then (useful-markdown-card.js?v=2:2)

**Comment by thomasloven** [comment]
Then the update failed, because if it was updated, you would get the error on line 3.

**Comment by SteveDinn** [comment]
You were right...I didn't refresh the page the right way, I guess...However, same error:

Uncaught (in promise) TypeError: Class extends value undefined is not a constructor or null
    at customElements.whenDefined.then (useful-markdown-card.js?v=3:3)

**Comment by SteveDinn** [comment]
Not sure if it was https://github.com/thomasloven/lovelace-useful-markdown-card/commit/58e0a5f20f626a9c4ff8fc03aa18ef51d96c9c51 or the card-tools update, but this is fixed for me now.
